steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - beta
      - run
      - deploy
      - demo-app-gke
      - "--image=gcr.io/$PROJECT_ID/demo-app:$SHORT_SHA"
      - "--set-env-vars=ENVIRONMENT=Cloud Run (GKE)"
      - "--platform=gke"
      - "--cluster=demo-cluster"
      - "--cluster-location=australia-southeast1-b"
