steps:
  - name: "gcr.io/$PROJECT_ID/envsubst"
    args: ["app.k8s.yaml"]
    env:
      - SHORT_SHA=$SHORT_SHA
    dir: "app"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container",
        "clusters",
        "get-credentials",
        "demo-cluster",
        "--zone=australia-southeast1-b",
      ]
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "app.k8s.yaml"]
    env:
      - CLOUDSDK_COMPUTE_REGION=australia-southeast1-b
      - CLOUDSDK_COMPUTE_ZONE=australia-southeast1
      - CLOUDSDK_CONTAINER_CLUSTER=demo-cluster
    dir: "app"
