steps:
  # ============================================================================ #
  #                            📦 BUILD DOCKER IMAGE                            #
  # ============================================================================ #

  - id: docker-pull
    name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["-c", "docker pull -q gcr.io/$PROJECT_ID/${_IMAGE}:latest || exit 0"]

  - id: docker-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --quiet
      - --cache-from=gcr.io/$PROJECT_ID/${_IMAGE}:latest
      - --tag=gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA
      - --tag=gcr.io/$PROJECT_ID/${_IMAGE}:latest
      - .
    dir: ./src/app
    waitFor: ["docker-pull"]

  - id: docker-push
    name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA"]
    waitFor: ["docker-build"]

  # ============================================================================ #
  #                              🕹️ CLOUD FUNCTIONS                              #
  # ============================================================================ #

  - id: cloud-functions
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - ${_CLOUD_FUNCTIONS_APP}
      - --region=${_REGION}
      - --allow-unauthenticated
      - --trigger-http
      - --runtime=python38
      - --entry-point=main
      - --source=./
    dir: "src/app"
    waitFor: ["-"]

  # ============================================================================ #
  #                           💪 APP ENGINE (STANDARD)                           #
  # ============================================================================ #

  - id: app-engine-standard
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.standard.yaml
      - --version=$SHORT_SHA
      - --promote
      - --stop-previous-version
    dir: "src/app"
    waitFor: ["-"]

  # ============================================================================ #
  #                           🦾 APP ENGINE (FLEXIBLE)                           #
  # ============================================================================ #

  - id: app-engine-flexible
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.flex.yaml
      - --image-url=gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA
      - --version=$SHORT_SHA
      - --promote
      - --stop-previous-version
    dir: "src/app"
    waitFor: ["docker-push"]

  # ============================================================================ #
  #                                 🏃‍♀️ CLOUD RUN                                 #
  # ============================================================================ #

  - id: cloud-run-managed
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_CLOUD_RUN_APP}
      - --image=gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA
      - --platform=managed
      - --region=us-central1
    waitFor: ["docker-push"]

  # ============================================================================ #
  #                             🏃‍♂️ CLOUD RUN (ANTHOS)                            #
  # ============================================================================ #

  - id: cloud-run-anthos
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_CLOUD_RUN_ANTHOS_APP}
      - --image=gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA
      - --platform=gke
      - --cluster=${_GKE_CLUSTER}
      - --cluster-location=${_ZONE}
      - --namespace=default
    waitFor: ["docker-push"]

  # ============================================================================ #
  #                           ⚙️ GOOGLE COMPUTE ENGINE                           #
  # ============================================================================ #

  - id: compute-engine
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud compute start-iap-tunnel ${_COMPUTE_ENGINE_APP} 9000 \
          --local-host-port=localhost:9000 &

        # give tunnel time to connect
        sleep 15;

        curl -X PATCH https://localhost:9000/hooks/update-env \
        --silent --show-error --fail --insecure \
        --data '{ "key": "CONTAINER_IMAGE_TAG", "value": "$SHORT_SHA" }' \
        --header "Host: ${_COMPUTE_ENGINE_DOMAIN}" \
        --header 'Authorization: Basic YWRtaW46cGFzc3dvcmQ=' \
        --header 'Content-Type: application/json'
    waitFor: ["docker-push"]

  # ============================================================================ #
  #                       🚂 GOOGLE KUBERENTES ENGINE (GKE)                      #
  # ============================================================================ #

  - id: gke-1
    name: hairyhenderson/gomplate
    args: ["-f", "app.k8s.tmpl", "-o", "app.k8s.yaml"]
    dir: "src/app"
    waitFor: ["docker-push"]

  - id: gke-2
    name: gcr.io/cloud-builders/kubectl
    args: ["apply", "-f", "app.k8s.yaml"]
    dir: "src/app"
    waitFor: ["gke-1"]

# ============================================================================ #
#                                    Fin 🏁                                    #
# ============================================================================ #

images:
  - gcr.io/$PROJECT_ID/${_IMAGE}:latest
  - gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA
options:
  substitution_option: ALLOW_LOOSE
  env:
    - IMAGE=gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA
    - APP=${_GKE_APP}
    - DOMAIN=${_GKE_DOMAIN}
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_COMPUTE_ZONE=${_ZONE}
    - CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}
substitutions:
  _IMAGE: 7apps-demo
  _REGION: australia-southeast1
  _ZONE: australia-southeast1-a
  _CLOUD_RUN_APP: run
  _CLOUD_RUN_ANTHOS_APP: run-anthos
  _CLOUD_FUNCTIONS_APP: function
  _APPENGINE_STANDARD_APP: default
  _APPENGINE_FLEXIBLE_APP: flexible
  _COMPUTE_ENGINE_APP: compute
  _COMPUTE_ENGINE_DOMAIN: compute.7apps.cloud
  _GKE_CLUSTER: gke-cluster
  _GKE_APP: gke-app
  _GKE_DOMAIN: gke.7apps.cloud
timeout: 3600s
