steps:
  #========================================
  # 0. BUILD DOCKER IMAGE
  #========================================
  - id: "Build Docker image"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.image.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["-"]

  #========================================
  # 1. CLOUD FUNCTIONS
  #========================================
  - id: "Deploy: Cloud Functions"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["builds", "submit", "--config", "cloudbuild.cloudfunction.yaml"]
    waitFor: ["-"]

  #========================================
  # 2. APP ENGINE (STANDARD)
  #========================================
  - id: "Deploy: App Engine (Standard)"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["builds", "submit", "--config", "cloudbuild.appengine.yaml"]
    waitFor: ["-"]

  #========================================
  # 3. APP ENGINE (FLEXIBLE)
  #========================================
  - id: "Deploy: App Engine (Flexible)"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.appengineflex.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["Build Docker image"]

  #========================================
  # 4. CLOUD RUN
  #========================================
  - id: "Deploy: Cloud Run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.cloudrun.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["Build Docker image"]

  #========================================
  # 5. CLOUD RUN (ON GKE)
  #========================================
  - id: "Deploy: Cloud Run on GKE"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.cloudrunk8s.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["Build Docker image"]

  #========================================
  # 6. GOOGLE KUBERENTES ENGINE (GKE)
  #========================================
  - id: "Deploy: Google Kubernetes Engine (GKE)"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.k8s.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["Build Docker image"]

  #========================================
  # 7. CLOUD FUNCTIONS
  #========================================
  - id: "Deploy: Google Compute Engine (GCE)"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.compute.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["Build Docker image"]

timeout: 3600s
