steps:
  #========================================
  # 0. BUILD DOCKER IMAGE
  #========================================
  - id: "Build Docker image"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.container.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["-"]

  #========================================
  # 1. CLOUD FUNCTIONS
  #========================================
  - id: "Deploy: Cloud Functions"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "demo-function"
      - "--trigger-http"
      - "--runtime=python37"
      - "--entry-point=greeting"
      - "--set-env-vars=ENVIRONMENT=Cloud Function"
    dir: "app"
    waitFor: ["-"]

  #========================================
  # 2. APP ENGINE (STANDARD)
  #========================================
  - id: "Deploy: App Engine (Standard)"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.standard.yaml", "--promote", "--version=0"]
    dir: "app"
    waitFor: ["-"]

  #========================================
  # 3. APP ENGINE (FLEXIBLE)
  #========================================
  - id: "Deploy: App Engine (Flexible)"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "app.flex.yaml",
        "--promote",
        "--image-url=gcr.io/$PROJECT_ID/demo-app:$SHORT_SHA",
        "--version=0",
      ]
    dir: "app"
    waitFor: ["Build Docker image"]

  #========================================
  # 4. CLOUD RUN
  #========================================
  - id: "Deploy: Cloud Run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - beta
      - run
      - deploy
      - demo-app
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--image=gcr.io/$PROJECT_ID/demo-app:$SHORT_SHA"
      - "--region=us-central1"
      - "--set-env-vars=ENVIRONMENT=Cloud Run"
    waitFor: ["Build Docker image"]

  #========================================
  # 5. CLOUD RUN (ON GKE)
  #========================================
  - id: "Deploy: Cloud Run on GKE"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - beta
      - run
      - deploy
      - demo-app-gke
      - "--image=gcr.io/$PROJECT_ID/demo-app:$SHORT_SHA"
      - "--set-env-vars=ENVIRONMENT=Cloud Run (GKE)"
      - "--platform=gke"
      - "--cluster=demo-cluster"
      - "--cluster-location=australia-southeast1-b"
    waitFor: ["Build Docker image"]

  #========================================
  # 6. GOOGLE KUBERENTES ENGINE (GKE)
  #========================================
  - id: "Deploy: Google Kubernetes Engine (GKE)"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config",
        "cloudbuild.k8s.yaml",
        "--substitutions=SHORT_SHA=$SHORT_SHA",
      ]
    waitFor: ["Build Docker image"]

  #========================================
  # 7. GOOGLE COMPUTE ENGINE
  #========================================
  - id: "Deploy: Google Compute Engine (GCE)"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "instances"
      - "update-container"
      - "demo-instance"
      - "--zone=australia-southeast1-b"
      - "--container-image=gcr.io/$PROJECT_ID/demo-app:$SHORT_SHA"
      - "--container-env=ENVIRONMENT=Google Compute Engine"
      - "--container-mount-host-path"
      - "mount-path=/etc/letsencrypt,host-path=/tmp,mode=rw"
    waitFor: ["Build Docker image"]

timeout: 3600s
