steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "app.flex.yaml",
        "--promote",
        "--image-url=gcr.io/$PROJECT_ID/demo-app:$SHORT_SHA",
        "--version=0",
      ]
    dir: "app"
