steps:
  # ============================================================================ #
  #                            📦 BUILD DOCKER IMAGE                            #
  # ============================================================================ #

  - id: docker-build
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: bash
    args:
      - "-c"
      - |
        echo $SHORT_SHA > ./src/app/commit_sha.txt && \
        gcloud builds submit \
          --config=cloudbuild.container.yaml \
          --substitutions=SHORT_SHA=$SHORT_SHA,_IMAGE_NAME=${_IMAGE_NAME}
    waitFor: ["-"]

  # ============================================================================ #
  #                              🕹️ CLOUD FUNCTIONS                              #
  # ============================================================================ #

  - id: functions-deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - ${_CLOUD_FUNCTIONS_NAME}
      - --trigger-http
      - --runtime=python38
      - --entry-point=main
      - "--set-env-vars=APP_TITLE=Cloud Function"
      - --source=./
      - --quiet
    dir: "src/app"
    waitFor: ["-"]

  # ============================================================================ #
  #                           💪 APP ENGINE (STANDARD)                           #
  # ============================================================================ #

  - id: app-deploy-standard
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.standard.yaml
      - --promote
      - --version=$SHORT_SHA
      - --stop-previous-version
      - --quiet
    dir: "src/app"
    waitFor: ["-"]

  # ============================================================================ #
  #                           🦾 APP ENGINE (FLEXIBLE)                           #
  # ============================================================================ #

  - id: app-deploy-flexible
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.flex.yaml
      - --image-url=${_IMAGE_NAME}:$SHORT_SHA
      - --promote
      - --version=$SHORT_SHA
      - --stop-previous-version
      - --quiet
    dir: "src/app"
    waitFor: ["docker-build"]

  # ============================================================================ #
  #                                 🏃‍♀️ CLOUD RUN                                 #
  # ============================================================================ #

  - id: run-deploy-managed
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_CLOUD_RUN_NAME}
      - --image=${_IMAGE_NAME}:$SHORT_SHA
      - "--set-env-vars=APP_TITLE=Cloud Run"
      - --platform=managed
      - --allow-unauthenticated
      - --region=us-central1
      - --quiet
    waitFor: ["docker-build"]

  # ============================================================================ #
  #                             🏃‍♂️ CLOUD RUN (ANTHOS)                            #
  # ============================================================================ #

  - id: run-deploy-anthos
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_CLOUD_RUN_ANTHOS_NAME}
      - --image=${_IMAGE_NAME}:$SHORT_SHA
      - "--set-env-vars=APP_TITLE=Cloud Run: Anthos"
      - --platform=gke
      - --cluster=${_GKE_CLUSTER_NAME}
      - --cluster-location=${_ZONE}
      - --namespace=default
      - --quiet
    waitFor: ["docker-build"]

  # ============================================================================ #
  #                           ⚙️ GOOGLE COMPUTE ENGINE                           #
  # ============================================================================ #

  - id: update-compute-engine
    name: "gcr.io/cloud-builders/curl"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud compute start-iap-tunnel ${_COMPUTE_ENGINE_NAME} 9000 \
          --local-host-port=localhost:9000 &

        # wait for tunnel to connect
        sleep 10;

        curl -X PATCH https://localhost:9000/hooks/update-env \
        --silent --show-error --fail --insecure \
        --data '{ "key": "CONTAINER_IMAGE_TAG", "value": "$SHORT_SHA" }' \
        --header 'Authorization: Basic YWRtaW46cGFzc3dvcmQ=' \
        --header 'Content-Type: application/json'
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
    waitFor: ["docker-build"]

  # ============================================================================ #
  #                       🚂 GOOGLE KUBERENTES ENGINE (GKE)                      #
  # ============================================================================ #

  - id: update-kubernetes-engine
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - set
      - image
      - deployment/${_KUBERNETES_ENGINE_NAME}
      - ${_KUBERNETES_ENGINE_NAME}=${_IMAGE_NAME}:$SHORT_SHA
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}"
    waitFor: ["docker-build"]

# ============================================================================ #
#                                    Fin 🏁                                    #
# ============================================================================ #

timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
substitutions:
  _IMAGE_NAME: gcr.io/$PROJECT_ID/7apps-demo
  _REGION: australia-southeast1
  _ZONE: australia-southeast1-a
  _GKE_CLUSTER_NAME: gke-cluster
  _CLOUD_RUN_NAME: run
  _CLOUD_RUN_ANTHOS_NAME: run-anthos
  _CLOUD_FUNCTIONS_NAME: function
  _APPENGINE_STANDARD_NAME: default
  _APPENGINE_FLEXIBLE_NAME: flexible
  _KUBERNETES_ENGINE_NAME: gke-app
  _COMPUTE_ENGINE_NAME: compute
  _COMPUTE_ENGINE_DOMAIN: compute.7apps.cloud
