steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - beta
      - run
      - deploy
      - demo-app
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--image=gcr.io/$PROJECT_ID/demo-app:$SHORT_SHA"
      - "--region=us-central1"
      - "--set-env-vars=ENVIRONMENT=Cloud Run"
