apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 35.244.97.212
    networking.gke.io/managed-certificates: gke-dot-servian-dot-fun
spec:
  backend:
    serviceName: demo-app
    servicePort: 80
  rules:
    - host: gke.servian.fun
      http:
        paths:
          - backend:
              serviceName: demo-app
              servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: demo-app

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - image: gcr.io/servian-app-demo/demo-app:$SHORT_SHA
          name: demo-app
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "Kubernetes"
