service: default
runtime: python38
main: src

entrypoint: gunicorn -b :8080 -w 2 main:app

instance_class: B2

manual_scaling:
  instances: 1

env_variables:
  APP_TITLE: "App Engine: Standard"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
