# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

/* _______
  |____  /\
      / /  \   _ __  _ __  ___
     / / /\ \ | '_ \| '_ \/ __|
    / / ____ \| |_) | |_) \__ \
   /_/_/    \_\ .__/| .__/|___/
              | |   | |
              |_|   |_| ©2020 Servian */

/* Global variables --------------------------------------------------------- */

variable "project_id" { type = string }
variable "region" { type = string }
variable "zone" { type = string }
variable "src_dir" { type = string }

variable "domain" { type = string }
variable "email" { type = string }
variable "image_name" { type = string }

variable "services" {
  type = map(
    object({
      name        = string
      description = string
      domain      = string
    })
  )
}

/* Google Provider ---------------------------------------------------------- */

provider "google" {
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/siteverification"
  ]
}

provider "google-beta" {
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/siteverification"
  ]
}

/* Data --------------------------------------------------------------------- */

data "google_project" "project" {
  project_id = var.project_id
}

data "google_client_config" "default" {}

